import{i as m}from"./assets/vendor-DVYrn7a6.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=r(t);fetch(t.href,e)}})();const d=document.querySelector("#hero-scroll-btn"),u=document.querySelector("#about-artists");d&&u?d.addEventListener("click",()=>{u.scrollIntoView({behavior:"smooth",block:"start"})}):(console.log("Кнопка:",d),console.log("Секція:",u));const g=document.querySelector(".menu-icon"),y=document.querySelector(".close-icon"),l=document.querySelector(".mobile-menu");g.addEventListener("click",()=>{l.classList.remove("mobmenu-hidden"),document.body.classList.add("no-scroll")});y.addEventListener("click",()=>{l.classList.add("mobmenu-hidden"),document.body.classList.remove("no-scroll")});const b=document.querySelectorAll(".mobile-nav-list a");b.forEach(s=>{s.addEventListener("click",()=>{l.classList.add("mobmenu-hidden"),document.body.classList.remove("no-scroll")})});const p=document.querySelectorAll('a[href^="#"]');p.forEach(s=>{s.addEventListener("click",o=>{const r=s.getAttribute("href");if(r==="#")return;o.preventDefault(),document.querySelector(r).scrollIntoView({behavior:"smooth"})})});const L=document.querySelector(".mobile-menu .logo-icon");L.addEventListener("click",()=>{l.classList.add("mobmenu-hidden"),document.body.classList.remove("no-scroll")});const v="https://sound-wave.b.goit.study/api",f=4;async function _(s){const o=await fetch(`${v}/artists?page=${s}&limit=${f}`);if(!o.ok)throw new Error("Failed to fetch");return await o.json()}function E(s){return s.map(({_id:o,strArtist:r,strArtistThumb:i,genres:t,strBiographyEN:e})=>{const n=e||"",c=n.length>300?n.substring(0,300)+"...":n;return`
      <li class="artists__item artist-card">
        <div class="artist-card__img-thumb">
          <img src="${i}" alt="${r}" class="artists__card--img" loading="lazy">
        </div>
        <div class="artist__card--content">
          <ul class="artist__card--genres">
            ${t.map(a=>`<li class="artist__card--genre">${a}</li>`).join("")}
          </ul>
          <h4 class="artist__card--name">${r}</h4>
          <p class="artist__card--info">${c}</p>
          <button class="artist__card--btn" type="button" data-id="${o}">
            Learn More 
            <svg width="24" height="24"><use href="/icon/symbol-defs.svg#icon-play3"></use></svg>
          </button>
        </div>
      </li>`}).join("")}function S(s,o){if(!s)return;const r=E(o);s.insertAdjacentHTML("beforeend",r)}function q(){return{listElement:document.querySelector(".artists__list"),loadMoreBtn:document.querySelector(".artists__button"),loader:document.querySelector(".loader-backdrop")}}function w(){const{listElement:s,loadMoreBtn:o,loader:r}=q();let i=1;async function t(){r&&r.classList.remove("is-hidden"),o&&o.classList.add("is-hidden");try{const e=await _(i),n=Array.isArray(e)?e:e.results||e.artists||[],c=e.totalPages||0;if(n.length===0){m.info({message:"No artists found."});return}S(s,n);const a=n.length===f&&(c===0||i<c);if(o&&o.classList.toggle("is-hidden",!a),i>1&&s&&s.firstElementChild){const{height:h}=s.firstElementChild.getBoundingClientRect();window.scrollBy({top:h*2,behavior:"smooth"})}}catch(e){console.error("Помилка рендеру:",e),m.error({title:"Error",message:e.message})}finally{r&&r.classList.add("is-hidden")}}o&&o.addEventListener("click",()=>{i+=1,t()}),t()}w();
//# sourceMappingURL=index.js.map
